### ISSUE TITLE
Without Autolayout

### ISSUE THREAD

**Issue by chirag225** [iwasrobbed/RPFloatingPlaceholders#32] opened 2016-07-11 11:08 UTC
Placeholder label alignment issue in 6 and 6+ if i work with autoresizing

**Comment by iwasrobbed** [comment] 2016-09-13 00:55
Duplicate of https://github.com/iwasrobbed/RPFloatingPlaceholders/issues/18

**Closed by iwasrobbed** 2016-09-13 00:55 UTC
